### ISSUE TITLE
Error while launching the game 

### ISSUE THREAD

**Issue by Exterminator921** [ClonkAndre/IV-SDK-DotNet#1]
So I recently installed the mod to make some scripts but everytime I try to run the game I get this error : Unable to load IVSDKDotNet.asi : Error 126. Do you know what causes it ?

**Comment by ClonkAndre** [comment]
Thanks for the report. Make sure you've installed Visual C++ 2005 Redistributable x86 and DirectX June 2010 SDK.

**Error 126** usually means that you are missing some files. It would be nice if you can tell me which file is missing exactly. You just need to search for those files in your windows folder and tell me which ones are not in there:
- VCRUNTIME140D.dll
- ucrtbased.dll
- MSVCP140D.dll
- mscoree.dll

Thanks!

**Comment by Exterminator921** [comment]
Yeah it works! TYSM
