### ISSUE TITLE
update about the function CREATE_CHECKPOINT

### ISSUE THREAD

**Issue by elonezra** [ClonkAndre/IV-SDK-DotNet#18]
I did some research about this native function and i got in to those conclusions:
```
CREATE_CHECKPOINT(int type (https://gtamods.com/wiki/Checkpoints_(GTA_IV))
                                    , float x, float y, float z, 
                                      float point_x, 
                                      float point_y, 
                                      float point_z, 
                                      float size);
```
point_x, point_y, point_z - are the coordinate where you want the arrow, if you use the arrows type to point to.
size -  is the size of the check point. probably the radius.

**Comment by ClonkAndre** [comment]
So the x, y, z parameters are where the checkpoint gets created and the point_x, _point_y, point_z parameters would be the coordinates where the checkpoint points to?

**Comment by elonezra** [comment]
indeed, you can see that clearly when you use the arrow type checkpoint. i made some tests with that and it pointed just where i wanted to point.
this one is very good for races and such.

**Comment by ClonkAndre** [comment]
It's very good for races indeed!
I'm gonna rename the parameters of the native function in the next version so they make more sense. Thanks!
