### ISSUE TITLE
Get nearest road

### ISSUE THREAD

**Issue by Exterminator921** [ClonkAndre/IV-SDK-DotNet#2]
Hey, I know I made a post not too long ago and I truly apologize for the time I take from you but I'm trying to spawn a car a bit far away from the player so I tried the GET_NEAREST_ROAD() native but I can figure out what the other overloads are for. can you help me ? 
![image](https://user-images.githubusercontent.com/70774814/198866572-45422dd7-453f-4a75-a017-83518d6b1f26.png)

**Comment by ClonkAndre** [comment]
You can maybe get more informations about those overloads on those websites below. They are very useful, i would recommend you to bookmark them.
https://pastebin.com/n7CAnpZB
https://gtamods.com/wiki/List_of_native_functions_(GTA_IV)

Just search for the native you want to get more information about and you might be lucky and it's better documented on one of the websites.

**Comment by Exterminator921** [comment]
Thank you very much!

**Comment by ClonkAndre** [comment]
I will publish 0.4 of IV-SDK .NET in a few minutes/hours which includes **CWorld.GetNextPositionOnStreet(Vector3 pos)** from which you can easily get the nearest street based on the **pos** parameter.
