### ISSUE TITLE
Can't enter Russian Shop on game's third mission "Three's a Crowd"

### ISSUE THREAD

**Issue by Ex3cutionerX** [ClonkAndre/IV-SDK-DotNet#29]
I can't enter the Russian shop in the third mission of the game storyline. I've tested it and concluded that it's IVSDK that's causing the issue. I tested without IVSDK on the same save file, and the brief introduction showing how to buy clothes in the store played normally. I also tested with IVSDK enabled but without any scripts, and the issue persists. When I approach the Russian shop and reach the yellow arrow on the door, nothing happens, and the door remains blocked, without triggering the tutorial on how to buy clothes. 

![GTAIV_sttgP4msPs](https://github.com/user-attachments/assets/8df3d55f-07ef-4788-8462-c53660176818)
I'm on GTA IV 1.0.7.0 with the latest ZolikaPatch, IVSDK 1.8, DXVK, and CryENB V3.

**Comment by ClonkAndre** [comment]
Thanks for the report!
I'm aware of this issue, and a fix for it will be in the next version which will release very soon.

**Comment by ClonkAndre** [comment]
This should be fixed now in [version 1.8.1](https://github.com/ClonkAndre/IV-SDK-DotNet/releases/tag/1.8.1).
