### ISSUE TITLE
The taxi (and probably other models) can't be spawned

### ISSUE THREAD

**Issue by Exterminator921** [ClonkAndre/IV-SDK-DotNet#3]
Hey it's me again, so this is a bit more urgent than my previous posts, it seems like C# automatically registers integer numbers over a certain number as unsigned ints so it's the case with the taxi model that can't spawn and automatically makes the game crash no matter how hard I try to convert its hash to an int. I don't have this problem with other models. Thank you in advance.

**Comment by ClonkAndre** [comment]
Use either the enum **eVehicle** and cast it to an int or use the native **GET_HASH_KEY("the_model_name")**. With both of those methods, i could spawn the Taxi without any problems.

**Comment by Exterminator921** [comment]
Ok really thank you you're a lifesaver
