### ISSUE TITLE
Text with coloured word like in missions

### ISSUE THREAD

**Issue by Exterminator921** [ClonkAndre/IV-SDK-DotNet#4]
Ok, i promise this is the last one, really, so i've made the mod that I wanted to make, but the only problem is that i'm looking for a way to display a text just like in the missions (screenshot below). Thank you in advance.
![image](https://user-images.githubusercontent.com/70774814/199311600-8cb84ff4-f80e-4963-a69b-477d229c2072.png)

**Comment by ClonkAndre** [comment]
Use **ShowSubtitleMessage** method which is the same as the native **PRINT_STRING_WITH_LITERAL_STRING_NOW** only shorter, and better to remember. The method has one overload that says how long the notification should stay (Default is 2000ms).

To make the text coloured, in your case you would need to write it like this: **ShowSubtitleMessage("Enter the ~y~shop~w~.");**

**~y~** means that the text should be drawed in yellow after this. **~w~** means that the text should be drawed in white again. You can also print game keys with this function for example: **~INPUT_PICKUP~** would print the key: "**E**".

More colours and keys can be found in the gxt entries for example **american.gxt**.

**Comment by Exterminator921** [comment]
Man again thank you're the goat.
