### ISSUE TITLE
Issue while creating peds

### ISSUE THREAD

**Issue by ARandom12** [ClonkAndre/IV-SDK-DotNet#6]
Hello there, i wanted to create a car with specific ped inside the car. I tried `create_char_inside_car` native and even `_task_warp_char_into_car_as_driver` but both makes the game crash. So can you guide any way to do this? Or can you upload an example related to car spawning and warping peds inside it?

**Comment by ClonkAndre** [comment]
I'm currently not into GTA IV Modding, but i will definitely try to help you once i'm back into Modding GTA IV!

**Comment by ARandom12** [comment]
> I'm currently not into GTA IV Modding, but i will definitely try to help you once i'm back into Modding GTA IV!

ohh sorry for bothering then.

**Comment by ARandom12** [comment]
I think you are back at GTA IV Modding again. So can you provide an example of spawning a car, with a ped inside of that car? 
In IVSDK it works but due to every frame in game thing i cannot do interval related tasks as using sleep, sleep_untill, and related functions causes game crash or game freeze and then a crash.

**Comment by ClonkAndre** [comment]
> I think you are back at GTA IV Modding again. So can you provide an example of spawning a car, with a ped inside of that car? In IVSDK it works but due to every frame in game thing i cannot do interval related tasks as using sleep, sleep_untill, and related functions causes game crash or game freeze and then a crash.

Can i see how you currently trying to create a char inside a car?

**Comment by ClonkAndre** [comment]
Close because of inactivity.
